// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gqlmodel

type Blah struct {
	ID *string `json:"id,omitempty"`
}

type CreateTodoInput struct {
	Text   string `json:"text"`
	UserID string `json:"userID"`
}

type Foo struct {
	ID *string `json:"id,omitempty"`
}

type Mutation struct {
}

type Query struct {
}
